<definition xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5" class="patch" id="oval:org.cisecurity:def:5745" version="17">
  <metadata>
    <title>DSA-4307-1 -- python3.5 -- security update</title>
    <affected family="unix">
      <platform>Debian 9</platform>
      <product>python3.5</product>
    </affected>
    <reference ref_id="DSA-4307-1" ref_url="https://www.debian.org/security/dsa-4307" source="VENDOR" />
    <reference ref_id="CVE-2017-1000158" ref_url="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-1000158" source="CVE" />
    <reference ref_id="CVE-2018-1060" ref_url="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-1060" source="CVE" />
    <reference ref_id="CVE-2018-1061" ref_url="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-1061" source="CVE" />
    <reference ref_id="CVE-2018-14647" ref_url="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-14647" source="CVE" />
    <description>Multiple security issues were discovered in Python.</description>
    <oval_repository>
      <dates>
        <submitted date="2018-10-12T11:11:22">
          <contributor organization="ALTX-SOFT">Alexandr Ruchkin</contributor>
        </submitted>
        <status_change date="2018-10-19T21:05:34.844-04:00">DRAFT</status_change>
        <status_change date="2018-11-02T04:00:06.144-04:00">INTERIM</status_change>
        <status_change date="2018-11-16T04:00:06.144-04:00">ACCEPTED</status_change>
      </dates>
      <status>ACCEPTED</status>
      <min_schema_version>5.10</min_schema_version>
    </oval_repository>
  </metadata>
  <criteria>
    <extend_definition comment="Debian 9 is installed" definition_ref="oval:org.cisecurity:def:2515" />
    <criterion comment="python3.5 is earlier than 0:3.5.3-1+deb9u1" test_ref="oval:org.cisecurity:tst:8676" />
  </criteria>
</definition>
